### ISSUE TITLE
vulnerable results 403 forbidden

### ISSUE THREAD

**Issue by jammasterj89** [wireghoul/dotdotpwn#14]
Hi,

I've ran dotdotpwn v3.0.2 against a web application that has reported 304 traversals.

I ran the following command:

./dotdotpwn.pl -m http -h xxxxxxxx -S -k "root"

All of the vulnerable traversals have a "?" in them, not sure if that is relevant. An example is:

[*] Testing Path (response analysis): https://xxxxxxxxxxx:443/?.%25c0%25af?.%25c0%25af?.%25c0%25af?.%25c0%25af?.%25c0%25af?.%25c0%25afetc%25c0%25afissue <- VULNERABLE!

But when I enter that URL into Chrome it comes back as 403 forbidden.

If it helps the server is running nginx v1.11.3

Thanks for your help!

**Comment by wireghoul** [comment]
Yes, the ? tends to cause fp on url fuzzing... try -k 'root:' instead of just root

**Comment by jammasterj89** [comment]
thanks @wireghoul. I've reran with "root:" and 0 traversals have been found.

**Comment by wireghoul** [comment]
They probably had root@localhost set as the contact email or something as keyword matching found root.
