### ISSUE TITLE
Ping reply as condition to continue the test 

### ISSUE THREAD

**Issue by mpwill** [wireghoul/dotdotpwn#15]
Hi! First of all, congratulations for the great App.

I would like to report a behavior I believe will help many users. In the HTTP_url.PM, the code dictates the app should terminate in case of a ping failure:

if(!$ping){
die "[-] Web server didn't respond !\n";

I was testing a windows box where firewall would not allow ping, and modifying the code allowed me to proceed with the test.

While by design, modifying the message to mention 'ping failure' as the cause would narrow down the issue for users.

Continue with your great projects! :)

**Comment by wireghoul** [comment]
By ping do you mean ICMP ping? It's not entirely clear to me what problem you're describing...

**Comment by wireghoul** [comment]
While your bug report still seems to confuse whatever you experienced with some other network protocol the -C command line switch probably solves your problem.
