### ISSUE TITLE
Changing port from default just shows 443

### ISSUE THREAD

**Issue by HadManySons** [wireghoul/dotdotpwn#17]
If I use -x $InsertPortNumberHere, in the banner before it runs it shows "Port: 443". When I omit the -x option, it then display the default port for the module selected. I've only tested this with the http module so far.

**Comment by Brumstar** [comment]
I found this issue today as well and wrote a fix in #18.

**Comment by wireghoul** [comment]
Unable to reproduce... it works for me:
root@bt:~/dotdotpwn# ./dotdotpwn.pl -x 8088 -m http -h 127.0.0.1
#################################################################################
#                                                                               #
#  CubilFelino                                                       Chatsubo   #
#  Security Research Lab              and            [(in)Security Dark] Labs   #
#  chr1x.sectester.net                             chatsubo-labs.blogspot.com   #
#                                                                               #
#                               pr0udly present:                                #
#                                                                               #
#  ________            __  ________            __  __________                   #
#  \______ \    ____ _/  |_\______ \    ____ _/  |_\______   \__  _  __ ____    #
#   |    |  \  /  _ \\   __\|    |  \  /  _ \\   __\|     ___/\ \/ \/ //    \   #
#   |    `   \(  <_> )|  |  |    `   \(  <_> )|  |  |    |     \     /|   |  \  #
#  /_______  / \____/ |__| /_______  / \____/ |__|  |____|      \/\_/ |___|  /  #
#          \/                      \/                                      \/   #
#                              - DotDotPwn v3.0.2 -                             #
#                         The Directory Traversal Fuzzer                        #
#                         http://dotdotpwn.sectester.net                        #
#                            dotdotpwn@sectester.net                            #
#                                                                               #
#                               by chr1x & nitr0us                              #
#################################################################################

[+] Report name: Reports/127.0.0.1_10-19-2017_02-38.txt

[========== TARGET INFORMATION ==========]
[+] Hostname: 127.0.0.1
[+] Protocol: http
[+] Port: 8088

I also tried it with -S just in case the port logic was flawed, but that worked too. If you can give me some steps to reproduce it I'll happily look at it, but it appears to be working fine for me without your patch.

**Comment by Brumstar** [comment]
You're right, this issue is not a problem in version v3.0.2. This issue exists on v3.0.0 which is what the Kali package installs, and I'd guess that's why @HadManySons saw it as well. Issue can be closed it looks like.

**Comment by wireghoul** [comment]
Thanks for the clarification :) closing issue.
