### ISSUE TITLE
Basic auth for http?

### ISSUE THREAD

**Issue by ralphtheninja** [wireghoul/dotdotpwn#23]
How can I give a user:password@host combination for a host that requires basic auth? Alternatively, can I set a header to produce the same result?

**Comment by wireghoul** [comment]
Take a look in EXAMPLES.txt for 2 solutions that should work

**Comment by ralphtheninja** [comment]
I've looked in EXAMPLES.txt but I couldn't find any example for http basic auth. I've tried using `-U` but couldn't get it to work.

**Comment by wireghoul** [comment]
Both the payload and stdout modules can be used for this.
