### ISSUE TITLE
Setting Authorization (or any other) Header

### ISSUE THREAD

**Issue by mpavelka** [wireghoul/dotdotpwn#24]
I would like to add an authorization header to requests in "http-url" module, maybe somewhat like with curl - `curl -H "authorization: Bearer ..."`:

```
dotdotpwn -m http-url -u https://example.com/foo?bar=TRAVERSAL -k "root:" -H "authorization: Bearer ..."
```

Is this feature in place? If so, I guess it needs to be better documented, otherwise I suggest implementing such feature.

**Comment by wireghoul** [comment]
See response to #23, I have no intention of adding any additional functionality for this, but you're welcome to submit a pull request.
