### ISSUE TITLE
Web Server (all-around-audit-solutions.com) Didn't Respond

### ISSUE THREAD

**Issue by principal-aaas** [wireghoul/dotdotpwn#25]
Hello!

Could you please help me resolve the issue that I am having when trying to dotdotpwn my website?  I downloaded the most recent version of dotdotpwn yesterday to my Kali Linux VM. I have been trying various commands, the latest being:
./dotdotpwn.pl -m http -h all-around-audit-solutions.com -M GET
The response that I keep receiving is:
Web server (all-around-audit-solutions.com) didn't respond !
Could this be because the website is hosted on a GoDaddy server?

Thank you very much for your time and best regards!  BTW, I am impressed with your tool as I was able to run it against other domains.

**Comment by wireghoul** [comment]
Two things:
1) Running this tool against a server which you do not own or have been granted permission to test for security may land you in legal trouble.
2) This appears to be a connectivity issue and not a code issue, you'll have to sort this out yourself
