### ISSUE TITLE
System-wide install

### ISSUE THREAD

**Issue by zar3bski** [wireghoul/dotdotpwn#26]
While trying to install **dotdotpwn** in a docker image, I noticed the following at run time when executing `dotdotpwn`

```
Cannot open User-Agents.txt file: No such file or directory at /usr/lib/perl5/vendor_perl/DotDotPwn/HTTP_Url.pm 
```

**dotdotpwn** was installed that way

```bash
cp -r dotdotpwn-3.0.2/DotDotPwn/ /usr/lib/perl5/vendor_perl
cp dotdotpwn-3.0.2/dotdotpwn.pl /usr/bin/dotdotpwn
```
Libraries are found from `/usr/lib/perl5/vendor_perl`, no problem, but this specific resource (`User-Agents.txt`) cannot be found by `HTTP_Url.pm` even-though it is right next to it
```bash
bash-5.0# ls /usr/lib/perl5/vendor_perl/DotDotPwn/
BisectionAlgorithm.pm  File.pm                HTTP.pm                Payload.pm             TFTP.pm                User-Agents.txt
FTP.pm                 Fingerprint.pm         HTTP_Url.pm            STDOUT.pm              TraversalEngine.pm
``` 
I do not know how relative path is handled by pearl but I wondered if my current problem had anything to do with this specific line
https://github.com/wireghoul/dotdotpwn/blob/98760e18acbff544a745bf871dbd4bd2640950a9/DotDotPwn/HTTP_Url.pm#L32

It might sound naive but, from the standpoint of `HTTP_Url.pm` , isn't `User-Agents.txt` supposed to be at `./User-Agents.txt` instead of `DotDotPwn/User-Agents.txt`? 

I am a complete noob with pearl so I am open to any cleaner way to install this tool system wide

**Comment by wireghoul** [comment]
This is not a project issue, there are Linux distros have packaged the project. Maybe look at their scripts or use their package.
