### ISSUE TITLE
using case

### ISSUE THREAD

**Issue by c4ir0** [wireghoul/dotdotpwn#30]
what is the right way to combine multiple key words to search in the files, Is it like : 

dotdotpwn -m http-url -u https://www.site/TRAVERSAL -k 'root:' 'secret' (space between words)

or 

dotdotpwn -m http-url -u https://www.site/TRAVERSAL -k 'root:', 'secret'  ( comma between words)

**Comment by wireghoul** [comment]
None of the files dotdotpwn will look for using the command you provided should contain the word secret, unless there was a username which had secret in it. I'm not sure what you're trying to do, but you probably need to implement your own solution.
