### ISSUE TITLE
Error load scriptlib perl

### ISSUE THREAD

**Issue by trev0rbr** [wireghoul/dotdotpwn#8]
after installed the perl module in mint distro

causes the error below

Can not locate TFTP.pm in @INC (you may need to install the TFTP module) (@INC contains:. / Etc / perl /usr/local/lib/perl/5.18.2 / usr / local / share / perl /5.18.2 / usr / lib / perl5 / usr / share / perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 / usr / local / lib / site_perl) at DotDotPwn / TFTP.pm line 13.

Solution
the line of code use TFTP;
you must place the following line because the module is in 'Net'
use Net ::TFTP; # / Usr / share / perl5 / Net / TFTP.pm

**Comment by wireghoul** [comment]
Net::TFTP is not the same Module as TFTP...
TFTP - http://search.cpan.org/~gsm/TFTP-1.0b3/TFTP.pm
Net::TFTP - http://search.cpan.org/~gbarr/Net-TFTP-0.19/TFTP.pm

While their interfaces looks quite similar I'm not certain that they are compatible, so unless you want to do the testing/write a patch I suggest you use the TFTP module.

**Comment by trev0rbr** [comment]
I'm using the module more like not found even after installed, the quick fix was to insert Net :: before the module call.

runs cool :)

**Comment by wireghoul** [comment]
Are you using the TFTP module or was this just to stop the error so you could use another module?

**Comment by trev0rbr** [comment]
I am using Net :: TFTP another module when running the script perl does not find the file in TFTP.pm base. I made this change in code and was a good. take a test. It is even interesting to have two module options to use.

**Comment by trev0rbr** [comment]
Congratulations tool. very useful lol
